//
//  Pokedex.swift
//  Pokedex
//
//  Created by leoni05 on 6/7/25.
//

import Foundation

class Pokedex {
    
    // MARK: - Properties
    
    static let shared = Pokedex()
    var pokemons = Array<PokemonModel>()
    private var pokemonMapper = Dictionary<String, Int>()

    // MARK: - Life Cycle
    
    private init() {
        pokemons = [
            PokemonModel(name: "팬텀", type: [.ghost, .poison], height: "1.5m", weight: "40.5kg", category: "그림자포켓몬",
                         desc: "생명을 빼앗기로 정한 먹잇감의 그림자에 숨어들어 꼼짝하지 않고 기회를 노린다.", engName: "Gengar", capturedDate: "2025/06/16", selected: true),
            PokemonModel(name: "기라티나", type: [.ghost, .dragon], height: "4.5m", weight: "750.0kg", category: "반골포켓몬",
                         desc: "이 세상의 이면에 있는 세계에 살고 있다고 전해지는 포켓몬이다. 고대의 무덤에 나타난다.", engName: "Giratina", capturedDate: "2025/06/30", selected: true),
            PokemonModel(name: "핫삼", type: [.bug, .steel], height: "1.8m", weight: "118.0kg", category: "집게포켓몬",
                         desc: "강철이 함유된 집게로 잡은 것은 아무리 딱딱해도 산산조각이 난다.", engName: "Scizor", capturedDate: "2025/06/12", selected: true),
            PokemonModel(name: "이상해씨", type: [.grass, .poison], height: "0.7m", weight: "6.9kg", category: "씨앗포켓몬",
                         desc: "태어나서 얼마 동안 등의 씨앗에 담긴 영양을 섭취하며 자란다.", engName: "Bulbasaur"),
            PokemonModel(name: "파이리", type: [.fire], height: "0.6m", weight: "8.5kg", category: "도롱뇽포켓몬",
                         desc: "꼬리에서 타오르는 불꽃은 생명력의 상징. 기운이 없으면 불꽃이 약해진다.", engName: "Charmander", capturedDate: "2025/06/12"),
            PokemonModel(name: "리자몽", type: [.fire, .flying], height: "1.7m", weight: "90.5kg", category: "화염포켓몬",
                         desc: "정말 화가 난 리자몽의 꼬리 끝 불꽃은 푸르스름하게 불타오른다.", engName: "Charizard", capturedDate: "2025/07/02"),
            PokemonModel(name: "꼬부기", type: [.water], height: "0.5m", weight: "9.0kg", category: "꼬마거북포켓몬",
                         desc: "태어난 뒤 등이 부풀면서 단단한 등껍질이 생긴다. 입에서 강력한 거품을 발사한다.", engName: "Squirtle"),
            PokemonModel(name: "어니부기", type: [.water], height: "1.0m", weight: "22.5kg", category: "거북포켓몬",
                         desc: "길고 탐스러운 꼬리는 장수의 상징이다. 노인층에게 특히 인기가 많다.", engName: "Wartortle"),
            PokemonModel(name: "피카츄", type: [.electric], height: "0.4m", weight: "6.0kg", category: "쥐포켓몬",
                         desc: "양 볼에는 전기를 저장하는 주머니가 있다. 화가 나면 저장한 전기를 단숨에 방출한다.", engName: "Pikachu"),
            PokemonModel(name: "라이츄", type: [.electric], height: "0.8m", weight: "30.0kg", category: "쥐포켓몬",
                         desc: "꼬리가 어스 역할을 하여 전기를 지면으로 흘려보내므로 자신은 감전되거나 하지 않는다.", engName: "Raichu"),
            PokemonModel(name: "삐삐", type: [.fairy], height: "0.6m", weight: "7.5kg", category: "요정포켓몬",
                         desc: "삐삐들은 보름달 밤에 어디에서 왔는지도 모르게 모여 춤춘다. 달빛을 받으면 떠오른다.", engName: "Clefairy"),
            PokemonModel(name: "식스테일", type: [.fire], height: "0.6m", weight: "9.9kg", category: "여우포켓몬",
                         desc: "자신보다 강한 상대에게 공격을 받으면 다친 척을 해서 속이고 그 틈을 타서 도망친다.", engName: "Vulpix"),
            PokemonModel(name: "나인테일", type: [.fire], height: "1.1m", weight: "19.9kg", category: "여우포켓몬",
                         desc: "9개의 꼬리에는 각각 다른 신비한 힘이 숨어 있다고 한다.", engName: "Ninetales"),
            PokemonModel(name: "푸린", type: [.normal, .fairy], height: "0.5m", weight: "5.5kg", category: "풍선포켓몬",
                         desc: "초롱초롱한 눈동자가 흔들릴 때 졸음이 쏟아지게 하는 이상하고 기분 좋은 노래를 부른다.", engName: "Jigglypuff"),
            PokemonModel(name: "푸크린", type: [.normal, .fairy], height: "1.0m", weight: "12.0kg", category: "풍선포켓몬",
                         desc: "얇고 고운 털을 지니고 있다. 화나게 하면 몸을 점점 부풀리며 덮쳐 오기 때문에 주의가 필요하다.", engName: "Wigglytuff"),
            PokemonModel(name: "디그다", type: [.ground], height: "0.2m", weight: "0.8kg", category: "두더지포켓몬",
                         desc: "지하 1m 정도를 파고들어 가서 나무뿌리 등을 씹어 먹고 산다. 가끔 지상으로 얼굴을 내민다.", engName: "Diglett"),
            PokemonModel(name: "닥트리오", type: [.ground], height: "0.7m", weight: "33.3kg", category: "두더지포켓몬",
                         desc: "3개의 머리가 교차하며 움직이는 것은 주변의 흙을 부드럽게 해 파기 쉽게 하기 위해서다.", engName: "Dugtrio"),
            PokemonModel(name: "나옹", type: [.normal], height: "0.4m", weight: "4.2kg", category: "요괴고양이포켓몬",
                         desc: "낮에는 거의 잠만 잔다. 밤이 되면 눈을 반짝이며 영역을 돌아다닌다.", engName: "Meowth"),
            PokemonModel(name: "고라파덕", type: [.water], height: "0.8m", weight: "19.6kg", category: "오리포켓몬",
                         desc: "항상 두통에 시달리고 있다. 이 두통이 심해지면 이상한 힘을 쓰기 시작한다.", engName: "Psyduck"),
            PokemonModel(name: "윈디", type: [.fire], height: "1.9m", weight: "155.0kg", category: "전설포켓몬",
                         desc: "초원을 내달리는 모습은 사람들의 마음을 사로잡았다고 옛날 그림에 묘사되어 있다.", engName: "Arcanine"),
            PokemonModel(name: "발챙이", type: [.water], height: "0.6m", weight: "12.4kg", category: "올챙이포켓몬",
                         desc: "배의 소용돌이는 피부 너머로 비쳐 보이는 내장의 일부다. 먹이를 먹으면 선명하게 보인다.", engName: "Poliwag"),
            PokemonModel(name: "야돈", type: [.water, .psychic], height: "1.2m", weight: "36.0kg", category: "얼간이포켓몬",
                         desc: "움직임이 둔하고 멍청하다. 맞아도 5초는 지나야 아픔을 느낄 정도다.", engName: "Slowpoke"),
            PokemonModel(name: "럭키", type: [.normal], height: "1.1m", weight: "34.6kg", category: "알포켓몬",
                         desc: "상처 입은 포켓몬이나 사람이 있으면 영양 만점의 알을 낳아 나눠 주는 상냥한 포켓몬이다.", engName: "Chansey"),
            PokemonModel(name: "아쿠스타", type: [.water, .psychic], height: "1.1m", weight: "80.0kg", category: "수수께끼포켓몬",
                         desc: "몸의 중심에 있는 빨간 핵에서 밤하늘을 향해 알 수 없는 전파를 발신한다.", engName: "Starmie"),
            PokemonModel(name: "잉어킹", type: [.water], height: "0.9m", weight: "10.0kg", category: "물고기포켓몬",
                         desc: "힘없는 한심한 포켓몬이다. 가끔 높이 뛰어오르지만 2m를 겨우 넘기는 게 고작이다.", engName: "Magikarp"),
            PokemonModel(name: "라프라스", type: [.water, .ice], height: "2.5m", weight: "220.0kg", category: "탈것포켓몬",
                         desc: "사람을 등에 태우고 바다를 건넌다. 기분이 좋으면 아름다운 목소리로 노래를 하기도 하는 듯하다.", engName: "Lapras"),
            PokemonModel(name: "메타몽", type: [.normal], height: "0.3m", weight: "4.0kg", category: "변신포켓몬",
                         desc: "변신은 완벽하지만 웃는 바람에 힘이 빠지면 변신이 풀려 버리고 만다.", engName: "Ditto"),
            PokemonModel(name: "이브이", type: [.normal], height: "0.3m", weight: "6.5kg", category: "진화포켓몬",
                         desc: "환경 변화에 곧바로 적응할 수 있도록 여러 형태로 진화할 수 있는 가능성을 가지고 있다.", engName: "Eevee"),
            PokemonModel(name: "샤미드", type: [.water], height: "1.0m", weight: "29.0kg", category: "거품뿜기포켓몬",
                         desc: "물가에 살지만 꼬리에 물고기처럼 지느러미가 남아 있어서 인어로 착각하는 사람도 있다.", engName: "Vaporeon"),
            PokemonModel(name: "쥬피썬더", type: [.electric], height: "0.8m", weight: "24.5kg", category: "번개포켓몬",
                         desc: "세포가 내고 있는 약한 전기를 하나로 모아서 강력한 전기를 발산한다.", engName: "Jolteon"),
            PokemonModel(name: "부스터", type: [.fire], height: "0.9m", weight: "25.0kg", category: "불꽃포켓몬",
                         desc: "들이마신 공기를 체내의 불꽃 주머니에 보내 1700도의 불꽃으로 내뿜는다.", engName: "Flareon"),
            PokemonModel(name: "암나이트", type: [.rock, .water], height: "0.4m", weight: "7.5kg", category: "소용돌이포켓몬",
                         desc: "현대의 우수한 과학 기술로 화석에서 부활한 포켓몬이다. 고대의 바다를 헤엄치고 있었다.", engName: "Omanyte"),
            PokemonModel(name: "잠만보", type: [.normal], height: "2.1m", weight: "460.0kg", category: "졸음포켓몬",
                         desc: "자고 있을 때를 제외하고는 항상 먹이를 먹고 있는 대식가. 하루에 400kg은 먹어 치운다.", engName: "Snorlax", capturedDate: "2025/06/10", selected: true),
            PokemonModel(name: "미뇽", type: [.dragon], height: "1.8m", weight: "3.3kg", category: "드래곤포켓몬",
                         desc: "세차게 떨어지는 폭포의 보호를 받으며 탈피를 거듭해 점점 크게 자란다.", engName: "Dratini"),
            PokemonModel(name: "신뇽", type: [.dragon], height: "4.0m", weight: "16.5kg", category: "드래곤포켓몬",
                         desc: "전신에서 오라를 발산하면 주변 날씨가 순식간에 변한다고 한다.", engName: "Dragonair"),
            PokemonModel(name: "망나뇽", type: [.dragon, .flying], height: "2.2m", weight: "210.0kg", category: "드래곤포켓몬",
                         desc: "드넓은 바다 어딘가에는 망나뇽만이 모여 사는 섬이 있다고 한다.", engName: "Dragonite", capturedDate: "2025/06/04", selected: true),
            PokemonModel(name: "뮤츠", type: [.psychic], height: "2.0m", weight: "122.0kg", category: "유전자포켓몬",
                         desc: "뮤의 유전자를 재구성해서 만들어졌다. 포켓몬 중에서 가장 난폭한 마음을 가지고 있다고 한다.", engName: "Mewtwo"),
            PokemonModel(name: "뮤", type: [.psychic], height: "0.4m", weight: "4.0kg", category: "신종포켓몬",
                         desc: "모든 기술을 사용하기 때문에 포켓몬의 조상이라고 생각하는 학자가 많다.", engName: "Mew"),
            PokemonModel(name: "치코리타", type: [.grass], height: "0.9m", weight: "6.4kg", category: "잎사귀포켓몬",
                         desc: "햇볕을 쬐는 것을 매우 좋아한다. 머리의 잎사귀를 사용해서 따뜻한 장소를 찾아낸다.", engName: "Chikorita"),
            PokemonModel(name: "브케인", type: [.fire], height: "0.5m", weight: "7.9kg", category: "불쥐포켓몬",
                         desc: "평소에는 몸을 웅크리고 있다. 화가 났을 때와 놀랐을 때 등에서 불꽃을 뿜어낸다.", engName: "Cyndaquil"),
            PokemonModel(name: "리아코", type: [.water], height: "0.6m", weight: "9.5kg", category: "큰턱포켓몬",
                         desc: "발달한 턱은 파워풀해서 뭐든지 깨물어 부수기 때문에 어버이 트레이너라도 주의해야 한다.", engName: "Totodile"),
            PokemonModel(name: "다꼬리", type: [.normal], height: "1.8m", weight: "32.5kg", category: "긴몸통포켓몬",
                         desc: "가늘고 긴 굴에서 새끼를 키운다. 새끼가 자라면 굴 밖에서 독립할 준비를 시킨다.", engName: "Furret"),
            PokemonModel(name: "피츄", type: [.electric], height: "0.3m", weight: "2.0kg", category: "아기쥐포켓몬",
                         desc: "전기를 모으는 게 서툴다. 조금만 충격을 받아도 금방 방전해 버린다.", engName: "Pichu"),
            PokemonModel(name: "삐", type: [.fairy], height: "0.3m", weight: "3.0kg", category: "별포켓몬",
                         desc: "유성이 반짝거리는 심야에 지그시 하늘을 바라보는 모습은 고향의 기억을 떠올리는 것 같다.", engName: "Cleffa"),
            PokemonModel(name: "토게피", type: [.fairy], height: "0.3m", weight: "1.5kg", category: "바늘알포켓몬",
                         desc: "껍질 안에 많은 행복이 가득 차 있어 상냥한 사람에게 행복을 나누어 준다고 한다.", engName: "Togepi"),
            PokemonModel(name: "전룡", type: [.electric], height: "1.4m", weight: "61.5kg", category: "라이트포켓몬",
                         desc: "꼬리의 빛은 멀리까지 전해지기 때문에 예전부터 봉화 역할로서 중요하게 여겨지고 있다.", engName: "Ampharos"),
            PokemonModel(name: "아르코", type: [.grass], height: "0.4m", weight: "5.8kg", category: "꽃포켓몬",
                         desc: "태양의돌의 영향으로 낮에 활동하게 되었다. 양지에서 춤추는 것을 좋아한다.", engName: "Bellossom"),
            PokemonModel(name: "마릴", type: [.water, .fairy], height: "0.4m", weight: "8.5kg", category: "물쥐포켓몬",
                         desc: "전신의 털은 물을 튕겨 내는 성질을 지녀 물을 끼얹어도 말라 있다.", engName: "Marill"),
            PokemonModel(name: "우파", type: [.water, .ground], height: "0.4m", weight: "8.5kg", category: "수어포켓몬",
                         desc: "온몸이 투명한 점막으로 뒤덮여 있으며 맨손으로 만지면 따끔따끔 저려 온다.", engName: "Wooper"),
            PokemonModel(name: "누오", type: [.water, .ground], height: "1.4m", weight: "75.0kg", category: "수어포켓몬",
                         desc: "느긋한 성격으로 늘 제멋대로 헤엄치다가 배의 밑바닥에 머리를 들이받곤 한다.", engName: "Quagsire"),
            PokemonModel(name: "에브이", type: [.psychic], height: "0.9m", weight: "26.5kg", category: "태양포켓몬",
                         desc: "상대의 움직임을 예지할 때 두 갈래로 갈라져 있는 꼬리의 끝이 미세하게 떨린다.", engName: "Espeon"),
            PokemonModel(name: "블래키", type: [.dark], height: "1.0m", weight: "27.0kg", category: "달빛포켓몬",
                         desc: "달의 파동을 몸에 쬐면 고리 모양이 희미하게 빛나며 이상한 힘에 눈을 뜬다.", engName: "Umbreon"),
            PokemonModel(name: "해피너스", type: [.normal], height: "1.5m", weight: "46.8kg", category: "행복포켓몬",
                         desc: "해피너스가 낳은 알을 한 입이라도 먹은 사람은 누구에게나 상냥해진다.", engName: "Blissey"),
            PokemonModel(name: "스이쿤", type: [.water], height: "2.0m", weight: "187.0kg", category: "오로라포켓몬",
                         desc: "세계 곳곳을 뛰어다니며 오염된 물을 정화시킨다. 북풍과 함께 떠나간다.", engName: "Suicune"),
            PokemonModel(name: "마기라스", type: [.rock, .dark], height: "2.0m", weight: "202.0kg", category: "갑옷포켓몬",
                         desc: "주변 지형을 바꾸는 정도쯤은 쉽게 해낼 정도의 힘을 가지고 있다. 주위를 신경 쓰지 않는 대담한 성격.", engName: "Tyranitar"),
            PokemonModel(name: "루기아", type: [.psychic, .flying], height: "5.2m", weight: "216.0kg", category: "잠수포켓몬",
                         desc: "깊은 해구의 밑바닥에서 잠잔다. 루기아가 날갯짓을 하면 40일 동안 폭풍우가 계속된다고 전해진다.", engName: "Lugia"),
            PokemonModel(name: "칠색조", type: [.fire, .flying], height: "3.8m", weight: "199.0kg", category: "무지개색포켓몬",
                         desc: "무지개색 날개를 가지고 있다. 칠색조를 본 사람은 영원한 행복이 약속된다고 한다.", engName: "Ho-Oh"),
            PokemonModel(name: "세레비", type: [.psychic, .grass], height: "0.6m", weight: "5.0kg", category: "시간이동포켓몬",
                         desc: "시간을 넘어 여기저기를 방황한다. 세레비가 모습을 나타낸 숲은 초목이 무성해진다고 한다.", engName: "Celebi"),
            PokemonModel(name: "나무지기", type: [.grass], height: "0.5m", weight: "5.0kg", category: "숲도마뱀포켓몬",
                         desc: "발바닥의 작은 가시가 벽이나 천장에 걸리므로 거꾸로 매달려도 떨어지지 않는다.", engName: "Treecko"),
            PokemonModel(name: "아차모", type: [.fire], height: "0.4m", weight: "2.5kg", category: "풋내기포켓몬",
                         desc: "몸속에 불꽃 주머니를 지니고 있어서 껴안으면 따끈따끈하다. 불꽃은 살아 있는 한 계속 불타오른다.", engName: "Torchic"),
            PokemonModel(name: "번치코", type: [.fire, .fighting], height: "1.9m", weight: "52.0kg", category: "맹화포켓몬",
                         desc: "강적을 만나면 손목에서 불꽃을 내뿜는다. 점프로 빌딩을 뛰어넘는 다릿심을 가졌다.", engName: "Blaziken"),
            PokemonModel(name: "물짱이", type: [.water], height: "0.4m", weight: "7.6kg", category: "늪물고기포켓몬",
                         desc: "큰 돌을 조각조각으로 부수는 파워를 가졌다. 강바닥에 쌓인 진흙에 몸을 묻고 쉰다.", engName: "Mudkip"),
            PokemonModel(name: "가디안", type: [.psychic, .fairy], height: "1.6m", weight: "48.4kg", category: "포용포켓몬",
                         desc: "트레이너를 지키기 위해서라면 사이코 파워를 모두 써서 작은 블랙홀을 만들어 낸다.", engName: "Gardevoir"),
            PokemonModel(name: "플러시", type: [.electric], height: "0.4m", weight: "4.2kg", category: "응원포켓몬",
                         desc: "몸에서 스파크를 일으켜서 동료를 응원한다. 전신주에 올라가서 전기를 흡수한다.", engName: "Plusle"),
            PokemonModel(name: "마이농", type: [.electric], height: "0.4m", weight: "4.2kg", category: "응원포켓몬",
                         desc: "마이농과 플러시의 전기는 혈액의 흐름을 좋게 하여 근육 결림을 푸는 효과가 있다.", engName: "Minun"),
            PokemonModel(name: "얼루기", type: [.normal], height: "1.1m", weight: "5.0kg", category: "얼룩팬더포켓몬",
                         desc: "똑같은 얼룩무늬의 얼루기는 없다. 휘청휘청거리는 걸음걸이로 상대의 노림수를 피한다.", engName: "Spinda"),
            PokemonModel(name: "파비코", type: [.normal, .flying], height: "0.4m", weight: "1.2kg", category: "솜새포켓몬",
                         desc: "솜 같은 날개를 손질하는 일은 절대 거르지 않는다. 더러워지면 물로 깨끗하게 씻는다.", engName: "Swablu"),
            PokemonModel(name: "파비코리", type: [.dragon, .flying], height: "1.1m", weight: "20.6kg", category: "허밍포켓몬",
                         desc: "마음이 서로 통한 사람이 있으면 부드럽고 아름다운 날개로 살짝 감싸고 허밍을 한다.", engName: "Altaria"),
            PokemonModel(name: "밀로틱", type: [.water], height: "6.2m", weight: "162.0kg", category: "사랑포켓몬",
                         desc: "무지개색이라고 전해지는 아름다운 비늘은 보는 방향을 바꾸면 여러 가지 색으로 변화한다.", engName: "Milotic"),
            PokemonModel(name: "앱솔", type: [.dark], height: "1.2m", weight: "47.0kg", category: "재난포켓몬",
                         desc: "재해의 위험을 감지한다. 위험을 알리는 때에만 사람 앞에 나타난다고 한다.", engName: "Absol"),
            PokemonModel(name: "대굴레오", type: [.ice, .water], height: "0.8m", weight: "39.5kg", category: "손뼉포켓몬",
                         desc: "유빙의 위를 데굴데굴 굴러서 해안에 다다른다. 헤엄치기에는 불편한 체형이다.", engName: "Spheal"),
            PokemonModel(name: "보만다", type: [.dragon, .flying], height: "1.5m", weight: "102.6kg", category: "드래곤포켓몬",
                         desc: "드디어 자라난 날개로 넓은 하늘을 날아다닌다. 기쁜 마음에 화염을 뿜어 일대를 불태워 버린다.", engName: "Salamence"),
            PokemonModel(name: "메타그로스", type: [.steel, .psychic], height: "1.6m", weight: "550.0kg", category: "무쇠다리포켓몬",
                         desc: "4개의 다리를 접어서 난다. 4개의 뇌는 슈퍼컴퓨터보다 우수하다고 전해진다.", engName: "Metagross"),
            PokemonModel(name: "그란돈", type: [.ground], height: "3.5m", weight: "950.0kg", category: "대륙포켓몬",
                         desc: "먼 옛날 가이오가와 사투를 벌인 후 지하 마그마 속에서 잠들어 있던 포켓몬이다.", engName: "Groudon"),
            PokemonModel(name: "레쿠쟈", type: [.dragon, .flying], height: "7.0m", weight: "206.5kg", category: "천공포켓몬",
                         desc: "구름보다 아득히 먼 위의 오존층에 서식하고 있기 때문에 지상에서 모습을 볼 수 없다.", engName: "Rayquaza"),
            PokemonModel(name: "지라치", type: [.steel, .psychic], height: "0.3m", weight: "1.1kg", category: "희망사항포켓몬",
                         desc: "1000년 중 7일 동안만 깨어나 모든 소원을 이루어 주는 능력을 발휘한다고 한다.", engName: "Jirachi"),
            PokemonModel(name: "모부기", type: [.grass], height: "0.4m", weight: "10.2kg", category: "어린잎포켓몬",
                         desc: "흙으로 만들어진 등껍질을 만져 보아 적당히 젖어 있다면 그 모부기는 매우 건강한 것이다.", engName: "Turtwig"),
            PokemonModel(name: "초염몽", type: [.fire, .fighting], height: "1.2m", weight: "55.0kg", category: "화염포켓몬",
                         desc: "스피드로 상대를 농락한다. 양팔 양다리를 활용한 독특한 방식으로 싸운다.", engName: "Infernape"),
            PokemonModel(name: "팽도리", type: [.water], height: "0.4m", weight: "5.2kg", category: "펭귄포켓몬",
                         desc: "걷는 것이 서툴러서 넘어질 때도 있지만 프라이드가 높은 팽도리는 신경 쓰지 않고 당당하게 가슴을 편다.", engName: "Piplup"),
            PokemonModel(name: "엠페르트", type: [.water, .steel], height: "1.7m", weight: "84.5kg", category: "황제포켓몬",
                         desc: "프라이드를 건드리는 자는 유빙까지도 절단하는 날개로 두 동강을 낸다.", engName: "Empoleon"),
            PokemonModel(name: "렌트라", type: [.electric], height: "1.4m", weight: "42.0kg", category: "안광포켓몬",
                         desc: "벽 저편까지 볼 수 있는 힘으로 도망친 먹이를 쫓는 것 이외에도 미아가 된 아이를 찾기도 한다.", engName: "Luxray"),
            PokemonModel(name: "파치리스", type: [.electric], height: "0.4m", weight: "3.9kg", category: "전기다람쥐포켓몬",
                         desc: "볼에 전기 주머니를 가진 포켓몬의 일종. 꼬리에 모인 전기를 방출한다.", engName: "Pachirisu"),
            PokemonModel(name: "흔들풍손", type: [.ghost, .flying], height: "0.4m", weight: "1.2kg", category: "풍선포켓몬",
                         desc: "풍선으로 착각해 흔들풍손을 가지고 있었던 어린아이가 사라지는 경우가 있다고 한다.", engName: "Drifloon"),
            PokemonModel(name: "딥상어동", type: [.dragon, .ground], height: "0.7m", weight: "20.5kg", category: "육지상어포켓몬",
                         desc: "구멍에 숨어서 먹이나 적이 지나가면 뛰쳐나가 문다. 기세가 대단해 이가 빠질 때도 있다.", engName: "Gible"),
            PokemonModel(name: "한카리아스", type: [.dragon, .ground], height: "1.9m", weight: "95.0kg", category: "마하포켓몬",
                         desc: "고속으로 달려나가면 날개가 공기의 칼날을 만들어 내고 이로 인해 주변의 나무는 절단된다.", engName: "Garchomp", capturedDate: "2025/06/01", selected: true),
            PokemonModel(name: "먹고자", type: [.normal], height: "0.6m", weight: "105.0kg", category: "대식가포켓몬",
                         desc: "매일 자신의 체중과 같은 양의 먹이가 필요하다. 맛에 대해서는 신경 쓰지 않는다.", engName: "Munchlax"),
            PokemonModel(name: "리오르", type: [.fighting], height: "0.7m", weight: "20.2kg", category: "파문포켓몬",
                         desc: "파동을 내서 동료끼리 의사소통을 한다. 밤새도록 계속 달릴 수 있다.", engName: "Riolu"),
            PokemonModel(name: "루카리오", type: [.fighting, .steel], height: "1.2m", weight: "54.0kg", category: "파동포켓몬",
                         desc: "파동을 포착하여 보이지 않는 상대의 모습도 볼 수 있다고 전해진다.", engName: "Lucario"),
            PokemonModel(name: "토게키스", type: [.fairy, .flying], height: "1.5m", weight: "38.0kg", category: "축복포켓몬",
                         desc: "다툼이 일어나는 장소에는 절대 나타나지 않는다. 최근에는 모습을 보기 어려워졌다.", engName: "Togekiss"),
            PokemonModel(name: "리피아", type: [.grass], height: "1.0m", weight: "25.5kg", category: "심록포켓몬",
                         desc: "맑은 날에 잠든 리피아는 광합성을 해서 깨끗한 공기를 만들어 낸다.", engName: "Leafeon"),
            PokemonModel(name: "글레이시아", type: [.ice], height: "0.8m", weight: "25.9kg", category: "신설포켓몬",
                         desc: "체온을 자유자재로 컨트롤해 대기의 수분을 얼려서 다이아몬드더스트를 일으킨다.", engName: "Glaceon"),
            PokemonModel(name: "레지기가스", type: [.normal], height: "3.7m", weight: "420.0kg", category: "거대포켓몬",
                         desc: "밧줄로 묶은 대륙을 당겨서 움직였다고 하는 전설이 남아 있다.", engName: "Regigigas"),
            PokemonModel(name: "다크라이", type: [.dark], height: "1.5m", weight: "50.5kg", category: "암흑포켓몬",
                         desc: "사람들을 깊은 잠으로 유인하여 꿈을 꾸게 하는 능력을 가지고 있다. 신월이 뜨는 밤에 활동한다.", engName: "Darkrai"),
            PokemonModel(name: "아르세우스", type: [.normal], height: "3.2m", weight: "320.0kg", category: "창조포켓몬",
                         desc: "1000개의 팔로 우주를 만든 포켓몬으로 신화에 묘사된다.", engName: "Arceus"),
            PokemonModel(name: "비크티니", type: [.psychic, .fire], height: "0.4m", weight: "4.0kg", category: "승리포켓몬",
                         desc: "승리를 부르는 포켓몬이다. 비크티니와 함께하는 트레이너는 그 어떤 승부에서도 승리한다고 한다.", engName: "Victini"),
            PokemonModel(name: "주리비얀", type: [.grass], height: "0.6m", weight: "8.1kg", category: "풀뱀포켓몬",
                         desc: "꼬리의 잎사귀로 햇빛을 받아서 에너지를 만들면 움직임이 재빨라지고 기술도 더욱 예리해진다.", engName: "Snivy"),
            PokemonModel(name: "샤로다", type: [.grass], height: "3.3m", weight: "63.0kg", category: "로열포켓몬",
                         desc: "햇빛으로 생성한 에너지를 기다란 몸속에서 수십 배로 증폭시킨다.", engName: "Serperior"),
            PokemonModel(name: "수댕이", type: [.water], height: "0.5m", weight: "5.9kg", category: "해달포켓몬",
                         desc: "배의 가리비칼을 작은 칼처럼 사용하여 적의 기술을 받아낸 다음 재빠르게 베어서 반격한다.", engName: "Oshawott"),
            PokemonModel(name: "엘풍", type: [.grass, .fairy], height: "0.7m", weight: "6.6kg", category: "바람숨기포켓몬",
                         desc: "아무리 좁은 틈이라도 바람처럼 빠져나간다. 하얀 털 뭉치를 남기고 간다.", engName: "Whimsicott"),
            PokemonModel(name: "조로아", type: [.dark], height: "0.7m", weight: "12.5kg", category: "나쁜여우포켓몬",
                         desc: "상대의 모습으로 둔갑하여 놀라게 한다. 말수가 적은 아이로 둔갑해 있을 때가 잦다고 한다.", engName: "Zorua"),
            PokemonModel(name: "조로아크", type: [.dark], height: "1.6m", weight: "81.1kg", category: "요괴여우포켓몬",
                         desc: "조로아크를 잡으려 한 사람을 환영의 경치 속에 가둬서 혼내 줬다고 전해진다.", engName: "Zoroark"),
            PokemonModel(name: "치라미", type: [.normal], height: "0.4m", weight: "5.8kg", category: "친칠라포켓몬",
                         desc: "자신의 몸이나 보금자리를 청소하느라 더러워진 꼬리는 깨끗한 샘물로 하루에 걸쳐서 씻는다.", engName: "Minccino"),
            PokemonModel(name: "치라치노", type: [.normal], height: "0.5m", weight: "7.5kg", category: "스카프포켓몬",
                         desc: "하얀 털은 특별한 기름으로 코팅되어 있어서 상대의 공격을 흘려 버린다.", engName: "Cinccino"),
            PokemonModel(name: "란쿨루스", type: [.psychic], height: "1.0m", weight: "20.1kg", category: "증폭포켓몬",
                         desc: "사이코 파워를 사용해 특수한 액체로 만들어진 팔을 조종해서 바위를 부순다.", engName: "Reuniclus"),
            PokemonModel(name: "에몽가", type: [.electric, .flying], height: "0.4m", weight: "5.0kg", category: "하늘다람쥐포켓몬",
                         desc: "전기를 내뿜으며 하늘을 춤추듯이 난다. 귀엽지만 성가시다.", engName: "Emolga"),
            PokemonModel(name: "샹델라", type: [.ghost, .fire], height: "1.0m", weight: "34.3kg", category: "권유포켓몬",
                         desc: "괴상한 불꽃으로 태워진 영혼은 갈 곳을 잃고 이승을 영원히 헤맨다.", engName: "Chandelure"),
            PokemonModel(name: "액스라이즈", type: [.dragon], height: "1.8m", weight: "105.5kg", category: "도끼턱포켓몬",
                         desc: "동굴이나 폐광산을 거처로 쓴다. 온순하지만 어금니를 건드리면 크게 화를 내기 때문에 주의가 필요하다.", engName: "Haxorus"),
            PokemonModel(name: "삼삼드래", type: [.dark, .dragon], height: "1.8m", weight: "160.0kg", category: "난폭포켓몬",
                         desc: "본체의 머리만이 뇌를 가지고 있다. 지능은 높지만 파괴하는 일만 생각하고 있다.", engName: "Hydreigon"),
            PokemonModel(name: "불카모스", type: [.bug, .fire], height: "1.6m", weight: "46.0kg", category: "태양포켓몬",
                         desc: "더운 곳에서는 타오르는 몸 때문에 미움을 받지만, 추운 곳에서는 태양의 화신이라며 받들어진다.", engName: "Volcarona"),
            PokemonModel(name: "레시라무", type: [.dragon, .fire], height: "3.2m", weight: "330.0kg", category: "백양포켓몬",
                         desc: "불꽃으로 세상을 태워버릴 수 있는 전설의 포켓몬. 진실의 세계를 구축하는 사람을 도와준다.", engName: "Reshiram"),
            PokemonModel(name: "제크로무", type: [.dragon, .electric], height: "2.9m", weight: "345.0kg", category: "흑음포켓몬",
                         desc: "번개로 세상을 태워버릴 수 있는 전설의 포켓몬. 이상의 세계를 구축하는 사람을 보좌한다.", engName: "Zekrom"),
            PokemonModel(name: "푸호꼬", type: [.fire], height: "0.4m", weight: "9.4kg", category: "여우포켓몬",
                         desc: "흥분하기 쉬운 성격이다. 체온도 과하게 오르기 때문에 귀로 열을 내보내 냉정을 유지한다.", engName: "Fennekin"),
            PokemonModel(name: "개구마르", type: [.water], height: "0.3m", weight: "7.0kg", category: "거품개구리포켓몬",
                         desc: "태평해 보이는 것은 적을 속이기 위한 연기다. 눈에 보이지 않는 스피드로 적을 압도한다.", engName: "Froakie"),
            PokemonModel(name: "개굴닌자", type: [.water, .dark], height: "1.5m", weight: "40.0kg", category: "시노비포켓몬",
                         desc: "목에 휘감은 기다란 혀에 닿는 공기의 흐름을 통해 보이지 않는 적의 동태를 살핀다.", engName: "Greninja"),
            PokemonModel(name: "파이어로", type: [.fire, .flying], height: "1.2m", weight: "24.5kg", category: "열화포켓몬",
                         desc: "비행 능력은 톱클래스다. 100kg 이상의 먹이를 잡은 채로도 가뿐히 날아다닌다.", engName: "Talonflame"),
            PokemonModel(name: "냐스퍼", type: [.psychic], height: "0.3m", weight: "3.5kg", category: "자제포켓몬",
                         desc: "체내의 강한 사이코 파워가 새어 나가지 않게 귀를 덮고 있으나 너무 오래 모아 두면 의식을 잃고 만다.", engName: "Espurr"),
            PokemonModel(name: "나룸퍼프", type: [.fairy], height: "0.4m", weight: "3.5kg", category: "솜사탕포켓몬",
                         desc: "하루에 자신의 체중만큼의 설탕을 먹는다. 당분이 부족하면 매우 기분이 나빠진다.", engName: "Swirlix"),
            PokemonModel(name: "님피아", type: [.fairy], height: "1.0m", weight: "23.5kg", category: "연결포켓몬",
                         desc: "리본 같은 더듬이를 통해 적의를 없애는 치유의 파동을 상대에게 보낸다.", engName: "Sylveon"),
            PokemonModel(name: "데덴네", type: [.electric, .fairy], height: "0.2m", weight: "2.2kg", category: "안테나포켓몬",
                         desc: "몸집이 작고 발전 기관이 미숙하기 때문에 사람이 사는 집의 전기를 꼬리를 통해 흡수해서 충전한다.", engName: "Dedenne"),
            PokemonModel(name: "미끄메라", type: [.dragon], height: "0.3m", weight: "2.8kg", category: "연체포켓몬",
                         desc: "몸의 대부분이 수분이다. 건조해서 말라 버리지 않도록 점막으로 전신을 뒤덮고 있다.", engName: "Goomy"),
            PokemonModel(name: "미끄래곤", type: [.dragon], height: "2.0m", weight: "150.5kg", category: "드래곤포켓몬",
                         desc: "비를 매우 좋아한다. 비가 내리는 날이면 산과 들을 거니는 모습을 볼 수 있는 온화한 성격의 포켓몬.", engName: "Goodra"),
            PokemonModel(name: "디안시", type: [.rock, .fairy], height: "0.7m", weight: "8.8kg", category: "보석포켓몬",
                         desc: "멜리시의 돌연변이다. 분홍빛으로 빛나는 몸은 세계에서 가장 아름답다고 일컬어진다.", engName: "Diancie"),
            PokemonModel(name: "나몰빼미", type: [.grass, .flying], height: "0.3m", weight: "1.5kg", category: "풀깃포켓몬",
                         desc: "전혀 소리를 내지 않고 활공하여 적에게 빠르게 접근한다. 눈치채기 전에 강렬한 발차기를 퍼붓는다.", engName: "Rowlet"),
            PokemonModel(name: "모크나이퍼", type: [.grass, .ghost], height: "1.6m", weight: "36.6kg", category: "화살깃포켓몬",
                         desc: "날개에 숨겨진 살깃을 시위에 메겨서 날린다. 100m 앞의 작은 돌도 관통하는 정밀함이다.", engName: "Decidueye"),
            PokemonModel(name: "따라큐", type: [.ghost, .fairy], height: "0.2m", weight: "0.7kg", category: "탈포켓몬",
                         desc: "볕이 들지 않는 어두운 곳에 산다. 사람들 앞에 나타날 때는 피카츄를 본뜬 천으로 온몸을 가린다.", engName: "Mimikyu"),
            PokemonModel(name: "염버니", type: [.fire], height: "0.3m", weight: "4.5kg", category: "토끼포켓몬",
                         desc: "전신이 따뜻해지면 본래의 힘을 발휘할 수 있다. 그러기 위해 준비 운동을 한다.", engName: "Scorbunny"),
            PokemonModel(name: "멍파치", type: [.electric], height: "0.3m", weight: "13.5kg", category: "강아지포켓몬",
                         desc: "달릴 때 꼬리가 시작되는 부분에서 전기를 만들어 낸다. 가라르에서는 양치기로 인기가 많다.", engName: "Yamper"),
            PokemonModel(name: "누니머기", type: [.ice, .bug], height: "0.3m", weight: "3.8kg", category: "애벌레포켓몬",
                         desc: "땅에 쌓인 눈이 먹이다. 새로 내린 부드러운 눈을 좋아해서 산꼭대기를 향해 먹으며 움직인다.", engName: "Snom"),
            PokemonModel(name: "나오하", type: [.grass], height: "0.4m", weight: "4.1kg", category: "풀고양이포켓몬",
                         desc: "복슬복슬한 털은 식물에 가까운 성분으로 이루어져 있다. 수시로 세수를 하면서 건조해지는 것을 방지한다.", engName: "Sprigatito"),
            PokemonModel(name: "빠모", type: [.electric], height: "0.3m", weight: "2.5kg", category: "쥐포켓몬",
                         desc: "볼의 전기 주머니가 아직 발달하지 않았다. 앞발의 볼록살을 열심히 비벼야 겨우 전기가 만들어진다.", engName: "Pawmi"),
            PokemonModel(name: "빠모트", type: [.electric, .fighting], height: "0.4m", weight: "6.5kg", category: "쥐포켓몬",
                         desc: "무리가 공격을 받으면 전격을 날리는 격투기로 먼저 싸움을 걸고 적을 쓰러뜨린다.", engName: "Pawmo")
        ]
        
        for idx in 0..<pokemons.count {
            pokemons[idx].pokedexNumber = idx+1
            pokemonMapper[pokemons[idx].engName.uppercased()] = idx
        }
    }
}

// MARK: - Extensions

extension Pokedex {
    func getPokemon(engName: String) -> PokemonModel? {
        let upperCasedEngName = engName.uppercased()
        if let idx = pokemonMapper[upperCasedEngName] {
            return pokemons[idx]
        }
        return nil
    }
}
